### ISSUE TITLE
6장 오탈자입니다. 소스 수정 부탁드릴께요.

### ISSUE THREAD

**Issue by ghost** [wikibook/ng2-book#1]
152페이지 3째줄
- routing -> AppRoutingModule이 적합할 것 같습니다.

155페이지 title.component.ts 예제
- templateUrl -> template
- 백틱 마지막에 콤마(,) 제거 필요

155페이지
- app-routing.module.ts -> user.service.ts

157페이지
- app-routing.module.ts -> app.module.ts

172페이지 app-routing.module.ts
loadChildren: 'app/player/player.module#PlayerModel' -> './player/player.module#PlayerModel'

**Comment by happygrammer** [comment]
안녕하세요. pshcode님.

책을 꼼꼼히 확인해 주시고 오·탈자를 꼼꼼히 점검해 주셔서 감사드립니다.

오·탈자가 있었던 점에 대해 미안한 마음이 큽니다.

- 전반적으로 문의 주신 내용은 오·탈자가 맞으며 오·탈자 등록을 해두도록 하겠습니다.
	- 문의 주신 내용 중 155p는 [2.x]에서 templateUrl로 해도 URL이 아닌 경우 예외처리를 템플릿 코드로 동작하도록 되어 있는 것으로 확인되었습니다. 이 때문에 코드 디버깅 시 templateUrl에 템플릿 코드가 포함되어 있었지만 확인을 못 했던 저의 실수가 있었습니다. 따라서, 의견 주셨던 대로 코드 내용을 수정했습니다.

- 다만 예외적으로, 172p의 코드 내용중 모듈 경로는 의도한 코드이기 때문에 현존 코드 그대로 유지하도록 하겠습니다.

다시 한번 감사드립니다.

ps : 새해 복 많이 받으세요.
